ARG FROM_TAG=latest
FROM ghcr.io/dimensionalos/base-ros-python:${FROM_TAG}

ARG GIT_COMMIT=unknown
ARG GIT_BRANCH=unknown

RUN apt-get install -y \
    git \
    git-lfs \
    nano \
    vim \
    ccze \
    tmux \
    htop \
    python-is-python3 \
    iputils-ping \
    wget

# Configure git to trust any directory (resolves dubious ownership issues in containers)
RUN git config --global --add safe.directory '*'

COPY docker/dev/dev-requirements.txt /app/
RUN --mount=type=cache,target=/root/.cache/pip pip install -r dev-requirements.txt

# Copy files and add version to motd
COPY /assets/dimensionalascii.txt /etc/motd
COPY /docker/dev/bash.sh /root/.bash.sh
COPY /docker/dev/tmux.conf /root/.tmux.conf

RUN echo "  v_${GIT_BRANCH}:${GIT_COMMIT} | $(date)" >> /etc/motd
RUN echo "echo -e '\033[34m$(cat /etc/motd)\033[0m\n'" >> /root/.bashrc

RUN echo "source /root/.bash.sh" >> /root/.bashrc

COPY /docker/dev/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
