# Copyright 2025 Dimensional Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

from io import BytesIO
import struct


class RobotState(object):
    msg_name = "sensor_msgs.RobotState"

    __slots__ = ["state", "mode", "error_code", "warn_code", "cmdnum", "mt_brake", "mt_able"]

    __typenames__ = ["int32_t", "int32_t", "int32_t", "int32_t", "int32_t", "int32_t", "int32_t"]

    __dimensions__ = [None, None, None, None, None, None, None]

    def __init__(self, state=0, mode=0, error_code=0, warn_code=0, cmdnum=0, mt_brake=0, mt_able=0):
        # LCM Type: int32_t
        self.state = state
        # LCM Type: int32_t
        self.mode = mode
        # LCM Type: int32_t
        self.error_code = error_code
        # LCM Type: int32_t
        self.warn_code = warn_code
        # LCM Type: int32_t
        self.cmdnum = cmdnum
        # LCM Type: int32_t
        self.mt_brake = mt_brake
        # LCM Type: int32_t
        self.mt_able = mt_able

    def lcm_encode(self):
        """Encode for LCM transport (dimos uses lcm_encode method name)."""
        return self.encode()

    def encode(self):
        buf = BytesIO()
        buf.write(RobotState._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(
            struct.pack(
                ">iiiiiii",
                self.state,
                self.mode,
                self.error_code,
                self.warn_code,
                self.cmdnum,
                self.mt_brake,
                self.mt_able,
            )
        )

    @classmethod
    def lcm_decode(cls, data: bytes):
        """Decode from LCM transport (dimos uses lcm_decode method name)."""
        return cls.decode(data)

    @classmethod
    def decode(cls, data: bytes):
        if hasattr(data, "read"):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != cls._get_packed_fingerprint():
            raise ValueError("Decode error")
        return cls._decode_one(buf)

    @classmethod
    def _decode_one(cls, buf):
        self = RobotState()
        (
            self.state,
            self.mode,
            self.error_code,
            self.warn_code,
            self.cmdnum,
            self.mt_brake,
            self.mt_able,
        ) = struct.unpack(">iiiiiii", buf.read(28))
        return self

    @classmethod
    def _get_hash_recursive(cls, parents):
        if cls in parents:
            return 0
        tmphash = (0x40A67674D7F79A43) & 0xFFFFFFFFFFFFFFFF
        tmphash = (((tmphash << 1) & 0xFFFFFFFFFFFFFFFF) + (tmphash >> 63)) & 0xFFFFFFFFFFFFFFFF
        return tmphash

    _packed_fingerprint = None

    @classmethod
    def _get_packed_fingerprint(cls):
        if cls._packed_fingerprint is None:
            cls._packed_fingerprint = struct.pack(">Q", cls._get_hash_recursive([]))
        return cls._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", RobotState._get_packed_fingerprint())[0]
