#!/usr/bin/env python3
# Copyright 2026 Dimensional Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Auto-generated by build_pip_dependency_database.py -- DO NOT EDIT BY HAND

from __future__ import annotations

from importlib.resources import files
import json
import re
from typing import Any

try:
    import tomllib
except ModuleNotFoundError:  # pragma: no cover - fallback for older interpreters
    import tomli as tomllib  # type: ignore


def _read_text(name: str) -> str:
    res = files("pyz_app").joinpath(name)
    return res.read_text()


DOCKERFILE_TEMPLATE: str = _read_text("bundled_files/Dockerfile")
PROJECT_TOML: dict[str, Any] = tomllib.loads(_read_text("bundled_files/pyproject.toml"))
PIP_DEP_DATABASE: dict[str, Any] = json.loads(
    _read_text("bundled_files/pip_dependency_database.json") or "{}"
)
FLAKE_TEMPLATE: str = _read_text("bundled_files/flake.nix")

APT_DEPENDENCIES = sorted(
    {dep for entry in PIP_DEP_DATABASE.values() for dep in entry.get("apt_dependencies", [])}
)
BREW_DEPENDENCIES = sorted(
    {dep for entry in PIP_DEP_DATABASE.values() for dep in entry.get("brew_dependencies", [])}
)
NIX_DEPENDENCIES = sorted(
    {dep for entry in PIP_DEP_DATABASE.values() for dep in entry.get("nix_dependencies", [])}
)


MANUAL_HUMAN_NAME_OVERRIDES = {
    "alsa-lib": "alsa",
    "assimp": "assimp",
    "at-spi2-atk": "at-spi2",
    "at-spi2-core": "at-spi2",
    "blas": "blas",
    "build-essential": "build-essential",
    "ca-certificates": "ca-certificates",
    "cacert": "ca-certificates",
    "can-utils": "can-utils",
    "cargo": "rust",
    "cmake": "cmake",
    "cuda-toolkit-12-0": "cuda",
    "cudapackages.cudatoolkit": "cuda",
    "cudaPackages.cudatoolkit": "cuda",
    "cudapackages.cudnn": "cudnn",
    "cudaPackages.cudnn": "cudnn",
    "cudatoolkit": "cuda",
    "cudnn": "cudnn",
    "curl": "curl",
    "cython3": "cython",
    "dbus": "dbus",
    "default-jdk": "java",
    "default-jre": "java",
    "eigen": "eigen",
    "ethtool": "ethtool",
    "fcl": "fcl",
    "ffmpeg": "ffmpeg",
    "fontconfig": "fontconfig",
    "freeglut": "freeglut",
    "freeglut3-dev": "freeglut",
    "fribidi": "fribidi",
    "g++": "gcc",
    "gcc-unwrapped.lib": "gcc",
    "gcc": "gcc",
    "geos": "geos",
    "gflags": "gflags",
    "gfortran": "gfortran",
    "gir1.2-gtk-3.0": "gtk",
    "git": "git",
    "git-lfs": "git-lfs",
    "glew": "glew",
    "glfw": "glfw",
    "glfw3": "glfw",
    "glib": "glib",
    "glibc": "glibc",
    "glog": "glog",
    "gmp": "gmp",
    "gnumake": "make",
    "gnutls": "gnutls",
    "gobject-introspection": "gobject-introspection",
    "gst-plugins-base": "gstreamer",
    "gstreamer": "gstreamer",
    "gtk+3": "gtk",
    "gtk3": "gtk",
    "harfbuzz": "harfbuzz",
    "hdf5": "hdf5",
    "iproute2": "iproute2",
    "jpeg-turbo": "lib jpeg turbo",
    "jpeg": "lib jpeg",
    "libjpeg-turbo8-dev": "lib jpeg turbo",
    "lapack": "lapack",
    "lcm": "lcm",
    "lcms2": "lcms",
    "leptonica": "leptonica",
    "libasound2-dev": "alsa",
    "libasound2": "alsa",
    "libassimp-dev": "assimp",
    "libatlas-base-dev": "atlas",
    "libatspi2.0-0": "at-spi2",
    "libavcodec-dev": "ffmpeg",
    "libavcodec58": "ffmpeg",
    "libavdevice-dev": "ffmpeg",
    "libavfilter-dev": "ffmpeg",
    "libavformat-dev": "ffmpeg",
    "libavformat58": "ffmpeg",
    "libavutil-dev": "ffmpeg",
    "libblas-dev": "blas",
    "libc++-dev": "libc++",
    "libc++abi-dev": "libc++",
    "libc6": "libc",
    "libcairo2-dev": "cairo",
    "libcairo2": "cairo",
    "libccd-dev": "ccd",
    "libccd": "ccd",
    "libcublas-12-0": "cublas",
    "libcublas-dev": "cublas",
    "libcuda?": "cuda",
    "libcudnn8-dev": "cudnn",
    "libcudnn8": "cudnn",
    "libcufft-12-0": "cufft",
    "libcups2": "cups",
    "libcurand-12-0": "curand",
    "libcusolver-12-0": "cusolver",
    "libcusparse-12-0": "cusparse",
    "libdbus-1-3": "dbus",
    "libdc1394-dev": "dc1394",
    "libdc1394": "dc1394",
    "libdrm": "drm",
    "libdrm2": "drm",
    "libedit-dev": "editline",
    "libedit": "editline",
    "libegl1-mesa-dev": "mesa",
    "libeigen3-dev": "eigen",
    "libfcl-dev": "fcl",
    "libffi-dev": "libffi",
    "libffi": "libffi",
    "libfontconfig1-dev": "fontconfig",
    "libfreetype6-dev": "freetype",
    "libfreetype6": "freetype",
    "libfribidi-dev": "fribidi",
    "libgflags-dev": "gflags",
    "libgfortran5": "gfortran",
    "libgirepository1.0-dev": "gobject-introspection",
    "libGL": "opengl",
    "libgl1-mesa-dev": "mesa",
    "libgl1-mesa-glx": "mesa",
    "libgles2-mesa-dev": "mesa",
    "libglew-dev": "glew",
    "libglfw3-dev": "glfw",
    "libglfw3": "glfw",
    "libglib2.0-0": "glib",
    "libGLU": "glu",
    "libglu1-mesa-dev": "mesa",
    "libgmp-dev": "gmp",
    "libgnutls30": "gnutls",
    "libgomp1": "openmp",
    "libgoogle-glog-dev": "glog",
    "libgstreamer-plugins-base1.0-0": "gstreamer",
    "libgstreamer1.0-0": "gstreamer",
    "libharfbuzz-dev": "harfbuzz",
    "libhdf5-dev": "hdf5",
    "libhdf5-serial-dev": "hdf5",
    "libidn2-0": "lib idn2",
    "libidn2": "lib idn2",
    "libimagequant-dev": "imagequant",
    "libimagequant": "imagequant",
    "libjpeg_turbo": "lib jpeg turbo",
    "libjpeg-dev": "lib jpeg",
    "libjpeg": "lib jpeg",
    "libjpeg62-turbo-dev": "lib jpeg turbo",
    "libjpeg8-dev": "lib jpeg",
    "liblcm-dev": "lcm",
    "liblcms2-dev": "lcms",
    "liblz4-dev": "lz4",
    "libmpc-dev": "mpc",
    "libmpc": "mpc",
    "libmpfr-dev": "mpfr",
    "libnettle8": "nettle",
    "libnspr4": "nspr",
    "libnss3": "nss",
    "liboctomap-dev": "octomap",
    "libomp-dev": "openmp",
    "libomp": "openmp",
    "libopenblas-dev": "openblas",
    "libopencv-dev": "opencv",
    "libopenjp2-7-dev": "openjpeg",
    "libopus-dev": "opus",
    "libopus": "opus",
    "libosmesa6-dev": "osmesa",
    "libpango-1.0-0": "pango",
    "libpng-dev": "lib png",
    "libpng": "lib png",
    "libportaudio2": "portaudio",
    "libportaudiocpp0": "portaudio",
    "libportmidi-dev": "portmidi",
    "libprotobuf-dev": "protobuf",
    "libqhull-dev": "qhull",
    "libsdl2-2.0-0": "sdl2",
    "libsdl2-dev": "sdl2",
    "libsdl2-image-2.0-0": "sdl2-image",
    "libsdl2-image-dev": "sdl2-image",
    "libsdl2-mixer-2.0-0": "sdl2-mixer",
    "libsdl2-mixer-dev": "sdl2-mixer",
    "libsdl2-ttf-2.0-0": "sdl2-ttf",
    "libsdl2-ttf-dev": "sdl2-ttf",
    "libsm": "x11-sm",
    "libsm6": "x11-sm",
    "libsndfile": "lib sndfile",
    "libsndfile1-dev": "lib sndfile",
    "libsndfile1": "lib sndfile",
    "libsodium-dev": "lib sodium",
    "libsodium": "lib sodium",
    "libspatialindex-dev": "spatialindex",
    "libspatialindex6": "spatialindex",
    "libsrtp": "srtp",
    "libsrtp2-dev": "srtp",
    "libssl-dev": "openssl",
    "libstdc++6": "gcc",
    "libswresample-dev": "ffmpeg",
    "libswscale-dev": "ffmpeg",
    "libswscale5": "ffmpeg",
    "libtasn1-6": "tasn1",
    "libtasn1": "tasn1",
    "libtbb-dev": "tbb",
    "libtesseract-dev": "tesseract",
    "libtiff-dev": "tiff",
    "libtiff": "tiff",
    "libturbojpeg": "lib jpeg turbo",
    "libturbojpeg0-dev": "lib jpeg turbo",
    "libudev-dev": "udev",
    "libunistring": "lib unistring",
    "libunistring2": "lib unistring",
    "libuv": "lib uv",
    "libuv1-dev": "lib uv",
    "libv4l-dev": "v4l",
    "libv4l": "v4l",
    "libvpx-dev": "vpx",
    "libvpx": "vpx",
    "libwebp-dev": "lib webp",
    "libwebp": "lib webp",
    "libx11-6": "x11",
    "libx11-dev": "x11",
    "libx264-dev": "x264",
    "libxcb-render0-dev": "x11",
    "libxcb-shm0-dev": "xcb",
    "libxcb-shm0": "xcb",
    "libxcb": "xcb",
    "libxcb1-dev": "xcb",
    "libxcomposite1": "xcomposite",
    "libxdamage1": "xdamage",
    "libxext-dev": "xext",
    "libxext": "xext",
    "libxext6": "xext",
    "libxfixes3": "xfixes",
    "libxft-dev": "xft",
    "libxft": "xft",
    "libXft": "xft",
    "libxi-dev": "xi",
    "libxinerama-dev": "xinerama",
    "libxinerama1": "xinerama",
    "libxkbcommon": "xkbcommon",
    "libxkbcommon0": "xkbcommon",
    "libxml2-dev": "lib xml 2",
    "libxml2": "lib xml 2",
    "libxrandr-dev": "xrandr",
    "libxrandr2": "xrandr",
    "libxrender-dev": "xrender",
    "libxrender": "xrender",
    "libxshmfence1?": "xshmfence",
    "libxvidcore-dev": "xvid",
    "libxxf86vm-dev": "xxf86vm",
    "libyaml-dev": "lib yaml",
    "libyaml": "lib yaml",
    "little-cms2": "lcms",
    "llvm_14": "llvm",
    "llvm-14-dev": "llvm",
    "llvm-14": "llvm",
    "llvm": "llvm",
    "llvm@14": "llvm",
    "llvmpackages.openmp": "openmp",
    "llvmPackages.openmp": "openmp",
    "lz4": "lz4",
    "make": "make",
    "mesa": "mesa",
    "mpfr": "mpfr",
    "nettle": "nettle",
    "ninja-build": "ninja",
    "ninja": "ninja",
    "nspr": "nspr",
    "nss": "nss",
    "nvidia-cuda-toolkit": "cuda",
    "octomap": "octomap",
    "openblas": "openblas",
    "opencv": "opencv",
    "opencv4": "opencv",
    "openjdk": "java",
    "openjpeg": "openjpeg",
    "openssl": "openssl",
    "openssl@3": "openssl",
    "opus": "opus",
    "pango": "pango",
    "patchelf": "patchelf",
    "pkg-config": "pkg-config",
    "portaudio": "portaudio",
    "portaudio19-dev": "portaudio",
    "portmidi": "portmidi",
    "protobuf-compiler": "protobuf",
    "protobuf": "protobuf",
    "pygobject3": "pygobject",
    "python3-dev": "python",
    "python3-opencv": "opencv",
    "python3-pip": "python",
    "python3-pyaudio": "pyaudio",
    "python3": "python",
    "qhull": "qhull",
    "rust": "rust",
    "rustc": "rust",
    "sdl2_image": "sdl2-image",
    "SDL2_image": "sdl2-image",
    "sdl2_mixer": "sdl2-mixer",
    "SDL2_mixer": "sdl2-mixer",
    "sdl2_ttf": "sdl2-ttf",
    "SDL2_ttf": "sdl2-ttf",
    "sdl2": "sdl2",
    "SDL2": "sdl2",
    "spatialindex": "spatialindex",
    "srtp": "srtp",
    "stdenv.cc.cc.lib": "gcc",
    "stdenv.cc": "gcc",
    "tbb": "tbb",
    "tcl-dev": "tcl",
    "tcl-tk": "tcl-tk",
    "tcl": "tcl",
    "tesseract": "tesseract",
    "tk-dev": "tk",
    "tk": "tk",
    "wget": "wget",
    "xorg-dev": "xorg",
    "xorg.libsm": "x11-sm",
    "xorg.libSM": "x11",
    "xorg.libX11": "x11",
    "xorg.libxcb": "x11",
    "xorg.libXcomposite": "xcomposite",
    "xorg.libXcursor": "xcursor",
    "xorg.libXdamage": "xdamage",
    "xorg.libXext": "xext",
    "xorg.libXfixes": "xfixes",
    "xorg.libXi": "xi",
    "xorg.libXinerama": "xinerama",
    "xorg.libXrandr": "xrandr",
    "xorg.libXrender": "xrender",
    "xorg.libXxf86vm": "xxf86vm",
    "xorg.xorgserver": "xorg",
    "xvfb-run": "xvfb",
    "xvfb": "xvfb",
    "zeromq": "zeromq",
    "zlib": "zlib",
    "zlib1g-dev": "zlib",
    "pkgs.ffmpeg_6": "ffmpeg",
    "pkgs.ffmpeg_6.dev": "ffmpeg",
}


def humanize_dependency(dep: str) -> str:
    name = dep.lower()
    if name in MANUAL_HUMAN_NAME_OVERRIDES:
        return MANUAL_HUMAN_NAME_OVERRIDES[name]
    name = name.split("@")[0]
    if name.startswith("pkgs."):
        name = name.split(".", 1)[1]
        if name.endswith(".dev"):
            name = name[:-4]
        if name in MANUAL_HUMAN_NAME_OVERRIDES:
            return MANUAL_HUMAN_NAME_OVERRIDES[name]

    if name.startswith("xorg."):
        name = name.split(".", 1)[1]
    if name.startswith("gtk+"):
        return "gtk"
    if name.startswith("llvm_"):
        return "llvm"
    if name.startswith("ffmpeg_"):
        return "ffmpeg"
    if name.startswith("sdl2"):
        return name.replace("_", "-")
    if name.startswith("cudapackages."):
        name = name.split(".", 1)[1]
    if "cuda" in name and "toolkit" in name:
        return "cuda"
    if name.startswith(("libav", "libsw")):
        return "ffmpeg"
    if name.startswith("libcudnn"):
        return "cudnn"
    if name.startswith("libcublas"):
        return "cublas"
    if name.startswith("libcufft"):
        return "cufft"
    if name.startswith("libcurand"):
        return "curand"
    if name.startswith("libcusolver"):
        return "cusolver"
    if name.startswith("libcusparse"):
        return "cusparse"
    if name.startswith("libsdl2-"):
        return name[3:]
    if "gstreamer" in name:
        return "gstreamer"

    if name.startswith("lib"):
        name = "lib " + name[3:]
    name = name.replace("_", " ").replace("+", "")
    name = name.strip("-")
    name = re.sub(r"(?:[-_.](?:dev|devel))$", "", name)
    name = re.sub(r"(?:[-_.]\d+(?:\.\d+)*(?:-?\d+)?)$", "", name)
    name = name.strip("-")
    return name


ALL_DEPENDENCIES = sorted(set(APT_DEPENDENCIES) | set(BREW_DEPENDENCIES) | set(NIX_DEPENDENCIES))
DEP_2_HUMAN_NAME = {dep: humanize_dependency(dep) for dep in ALL_DEPENDENCIES}
