# Copyright 2025-2026 Dimensional Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is auto-generated. Do not edit manually.
# Run `pytest dimos/robot/test_all_blueprints_generation.py` to regenerate.

all_blueprints = {
    "arm-teleop": "dimos.teleop.blueprints:arm_teleop",
    "arm-teleop-visualizing": "dimos.teleop.blueprints:arm_teleop_visualizing",
    "coordinator-basic": "dimos.control.blueprints:coordinator_basic",
    "coordinator-cartesian-ik-mock": "dimos.control.blueprints:coordinator_cartesian_ik_mock",
    "coordinator-cartesian-ik-piper": "dimos.control.blueprints:coordinator_cartesian_ik_piper",
    "coordinator-combined-xarm6": "dimos.control.blueprints:coordinator_combined_xarm6",
    "coordinator-dual-mock": "dimos.control.blueprints:coordinator_dual_mock",
    "coordinator-dual-xarm": "dimos.control.blueprints:coordinator_dual_xarm",
    "coordinator-mock": "dimos.control.blueprints:coordinator_mock",
    "coordinator-piper": "dimos.control.blueprints:coordinator_piper",
    "coordinator-piper-xarm": "dimos.control.blueprints:coordinator_piper_xarm",
    "coordinator-teleop-xarm6": "dimos.control.blueprints:coordinator_teleop_xarm6",
    "coordinator-velocity-xarm6": "dimos.control.blueprints:coordinator_velocity_xarm6",
    "coordinator-xarm6": "dimos.control.blueprints:coordinator_xarm6",
    "coordinator-xarm7": "dimos.control.blueprints:coordinator_xarm7",
    "demo-camera": "dimos.hardware.sensors.camera.module:demo_camera",
    "demo-error-on-name-conflicts": "dimos.robot.unitree_webrtc.demo_error_on_name_conflicts:demo_error_on_name_conflicts",
    "demo-google-maps-skill": "dimos.agents.skills.demo_google_maps_skill:demo_google_maps_skill",
    "demo-gps-nav": "dimos.agents.skills.demo_gps_nav:demo_gps_nav",
    "demo-grasping": "dimos.manipulation.grasping.demo_grasping:demo_grasping",
    "demo-object-scene-registration": "dimos.perception.demo_object_scene_registration:demo_object_scene_registration",
    "demo-osm": "dimos.mapping.osm.demo_osm:demo_osm",
    "demo-skill": "dimos.agents.skills.demo_skill:demo_skill",
    "dual-xarm6-planner": "dimos.manipulation.manipulation_blueprints:dual_xarm6_planner",
    "unitree-g1": "dimos.robot.unitree_webrtc.unitree_g1_blueprints:unitree_g1",
    "unitree-g1-agentic": "dimos.robot.unitree_webrtc.unitree_g1_blueprints:unitree_g1_agentic",
    "unitree-g1-agentic-sim": "dimos.robot.unitree_webrtc.unitree_g1_blueprints:unitree_g1_agentic_sim",
    "unitree-g1-basic": "dimos.robot.unitree_webrtc.unitree_g1_blueprints:unitree_g1_basic",
    "unitree-g1-basic-sim": "dimos.robot.unitree_webrtc.unitree_g1_blueprints:unitree_g1_basic_sim",
    "unitree-g1-detection": "dimos.robot.unitree_webrtc.unitree_g1_blueprints:unitree_g1_detection",
    "unitree-g1-full": "dimos.robot.unitree_webrtc.unitree_g1_blueprints:unitree_g1_full",
    "unitree-g1-joystick": "dimos.robot.unitree_webrtc.unitree_g1_blueprints:unitree_g1_joystick",
    "unitree-g1-shm": "dimos.robot.unitree_webrtc.unitree_g1_blueprints:unitree_g1_shm",
    "unitree-g1-sim": "dimos.robot.unitree_webrtc.unitree_g1_blueprints:unitree_g1_sim",
    "unitree-go2": "dimos.robot.unitree_webrtc.unitree_go2_blueprints:unitree_go2",
    "unitree-go2-agentic": "dimos.robot.unitree_webrtc.unitree_go2_blueprints:unitree_go2_agentic",
    "unitree-go2-agentic-huggingface": "dimos.robot.unitree_webrtc.unitree_go2_blueprints:unitree_go2_agentic_huggingface",
    "unitree-go2-agentic-mcp": "dimos.robot.unitree_webrtc.unitree_go2_blueprints:unitree_go2_agentic_mcp",
    "unitree-go2-agentic-ollama": "dimos.robot.unitree_webrtc.unitree_go2_blueprints:unitree_go2_agentic_ollama",
    "unitree-go2-basic": "dimos.robot.unitree_webrtc.unitree_go2_blueprints:unitree_go2_basic",
    "unitree-go2-detection": "dimos.robot.unitree_webrtc.unitree_go2_blueprints:unitree_go2_detection",
    "unitree-go2-ros": "dimos.robot.unitree_webrtc.unitree_go2_blueprints:unitree_go2_ros",
    "unitree-go2-spatial": "dimos.robot.unitree_webrtc.unitree_go2_blueprints:unitree_go2_spatial",
    "unitree-go2-temporal-memory": "dimos.robot.unitree_webrtc.unitree_go2_blueprints:unitree_go2_temporal_memory",
    "unitree-go2-vlm-stream-test": "dimos.robot.unitree_webrtc.unitree_go2_blueprints:unitree_go2_vlm_stream_test",
    "xarm6-planner-only": "dimos.manipulation.manipulation_blueprints:xarm6_planner_only",
    "xarm7-planner-coordinator": "dimos.manipulation.manipulation_blueprints:xarm7_planner_coordinator",
}


all_modules = {
    "arm_teleop_module": "dimos.teleop.quest.quest_extensions",
    "camera_module": "dimos.hardware.sensors.camera.module",
    "cartesian_motion_controller": "dimos.manipulation.control.servo_control.cartesian_motion_controller",
    "control_coordinator": "dimos.control.coordinator",
    "cost_mapper": "dimos.mapping.costmapper",
    "demo_calculator_skill": "dimos.agents.skills.demo_calculator_skill",
    "demo_robot": "dimos.agents.skills.demo_robot",
    "depth_module": "dimos.robot.unitree_webrtc.depth_module",
    "detection3d_module": "dimos.perception.detection.module3D",
    "detection_db_module": "dimos.perception.detection.moduleDB",
    "foxglove_bridge": "dimos.robot.foxglove_bridge",
    "g1_connection": "dimos.robot.unitree.connection.g1",
    "g1_sim_connection": "dimos.robot.unitree.connection.g1sim",
    "g1_skills": "dimos.robot.unitree_webrtc.unitree_g1_skill_container",
    "go2_connection": "dimos.robot.unitree.connection.go2",
    "google_maps_skill": "dimos.agents.skills.google_maps_skill_container",
    "gps_nav_skill": "dimos.agents.skills.gps_nav_skill",
    "grasping_module": "dimos.manipulation.grasping.grasping",
    "human_input": "dimos.agents.cli.human",
    "joint_trajectory_controller": "dimos.manipulation.control.trajectory_controller.joint_trajectory_controller",
    "keyboard_teleop": "dimos.robot.unitree_webrtc.keyboard_teleop",
    "llm_agent": "dimos.agents.agent",
    "manipulation_module": "dimos.manipulation.manipulation_module",
    "mapper": "dimos.robot.unitree_webrtc.type.map",
    "navigation_skill": "dimos.agents.skills.navigation",
    "object_scene_registration_module": "dimos.perception.object_scene_registration",
    "object_tracking": "dimos.perception.object_tracker",
    "osm_skill": "dimos.agents.skills.osm",
    "person_follow_skill": "dimos.agents.skills.person_follow",
    "person_tracker_module": "dimos.perception.detection.person_tracker",
    "quest_teleop_module": "dimos.teleop.quest.quest_teleop_module",
    "realsense_camera": "dimos.hardware.sensors.camera.realsense.camera",
    "replanning_a_star_planner": "dimos.navigation.replanning_a_star.module",
    "rerun_scene_wiring": "dimos.dashboard.rerun_scene_wiring",
    "ros_nav": "dimos.navigation.rosnav",
    "spatial_memory": "dimos.perception.spatial_perception",
    "speak_skill": "dimos.agents.skills.speak_skill",
    "temporal_memory": "dimos.perception.experimental.temporal_memory.temporal_memory",
    "twist_teleop_module": "dimos.teleop.quest.quest_extensions",
    "unitree_skills": "dimos.robot.unitree_webrtc.unitree_skill_container",
    "utilization": "dimos.utils.monitoring",
    "visualizing_teleop_module": "dimos.teleop.quest.quest_extensions",
    "vlm_agent": "dimos.agents.vlm_agent",
    "vlm_stream_tester": "dimos.agents.vlm_stream_tester",
    "voxel_mapper": "dimos.mapping.voxels",
    "wavefront_frontier_explorer": "dimos.navigation.frontier_exploration.wavefront_frontier_goal_selector",
    "web_input": "dimos.agents.cli.web",
    "websocket_vis": "dimos.web.websocket_vis.websocket_vis_module",
    "zed_camera": "dimos.hardware.sensors.camera.zed.camera",
}
